### ISSUE TITLE
PDF presentation

### ISSUE THREAD

**Issue by drphilmarshall** [dfm/triangle.py#41]
OK @dfm, here's a wishlist for those of us using triangle.py to plot samples drawn from PDFs:

* [x] Contour levels that enclose 68 and 95% of the 2D probability
* [x] Arbitrary levels, why not. (See #31)
* [x] Optional Gaussian smoothing of 2D PDFs for presentation purposes
* [x] Ditto for 1D histograms
* [x] Uniformly filled contours to show confidence regions without being distracted by the actual density

This might take you a while, sorry - let us know when you're done! Thanks Dan.

**Comment by dfm** [comment]
All of those options are in place now but I haven't finished documenting them... the docstring is actually pretty out of date so I should probably get on that.

**Comment by drphilmarshall** [comment]
Nice! Like the test_figures.
