### ISSUE TITLE
Smooth parameter must be a (not-necessarily integer) number of pixels

### ISSUE THREAD

**Issue by drphilmarshall** [dfm/triangle.py#45]
Seems to be in physical units at the moment.

**Comment by dfm** [comment]
I don't quite understand your comment... it should be in units of pixels already. The main annoyance is that currently it must be the same in every dimension.

**Comment by drphilmarshall** [comment]
Huh - that's good! But it must be some other behaviour I'm seeing then,
perhaps that the kwargs aren't getting passed though properly. Did you see
my attempt to upgrade the Dustin and my Mayacamas notebook? Feel free to
close this, apologies for jumping to conclusions!

On Mon, Apr 6, 2015 at 9:21 PM, Dan Foreman-Mackey <notifications@github.com

**Comment by dfm** [comment]
Can you post an example here where you're not getting the desired behavior?

**Comment by drphilmarshall** [comment]
Yeah - check out [this notebook](
http://nbviewer.ipython.org/github/drphilmarshall/LearningInference/blob/master/straightline.ipynb).
It seems not to want to obey my smoothing and contour filling instructions!

On Mon, Apr 6, 2015 at 9:51 PM, Dan Foreman-Mackey <notifications@github.com

**Comment by drphilmarshall** [comment]
Oh, and here's my forked and tweaked version of the [`demo.py` script](
https://github.com/drphilmarshall/triangle.py/blob/master/demo.py), where I
seem to have gotten the idea that the smoothing length was in physical
rather than image units...

**Comment by dfm** [comment]
In the notebook, it looks like you're not importing the updated version at all!

**Comment by dfm** [comment]
Make sure that you've installed the git master version somewhere where the notebook can find it. You'll also need to restart the kernel.

**Comment by drphilmarshall** [comment]
Thanks Dan - as predicted, I had an old pip-installed triangle_plot that
was dominating my python path. With this removed, the triangle plots are
now up to date in the straight line notebook. There's some odd behaviour
with the filled contours, [see what you think of the with-scatter results
plot, in the s dimension](
http://nbviewer.ipython.org/github/drphilmarshall/LearningInference/blob/master/straightline.ipynb).
I feel like I already solved this in CornerPlotter...

**Comment by dfm** [comment]
If you find the method you use to deal with cases like this, let me know cause I've never been able to find anything.

**Comment by dfm** [comment]
Never mind! I figured it out. Try pulling from master and making that plot again.

**Comment by drphilmarshall** [comment]
Ooh! I see what you did :-)
That *almost* works - just need to connect the dots the right way, now (see
the second triangle plot in [this notebook](
http://nbviewer.ipython.org/github/drphilmarshall/LearningInference/blob/master/straightline.ipynb
)

**Comment by dfm** [comment]
How about now?

**Comment by drphilmarshall** [comment]
That's fixed it! Nice work Daniel - thank you! :-)

On Tue, Apr 7, 2015 at 6:36 PM, Dan Foreman-Mackey <notifications@github.com
