### ISSUE TITLE
Image in readme.rst is down

### ISSUE THREAD

**Issue by amueller** [dfm/triangle.py#56]

**Comment by dfm** [comment]
I think this is actually a GitHub cache problem because https://raw.githubusercontent.com/dfm/triangle.py/master/README.rst is barfing too...

**Comment by dfm** [comment]
(as is https://raw.githubusercontent.com/scikit-learn/scikit-learn/master/README.rst :smile:)

**Comment by amueller** [comment]
Right, I get unicorns. Sorry for the noise.
