### ISSUE TITLE
Time for a new pip package?

### ISSUE THREAD

**Issue by drphilmarshall** [dfm/triangle.py#58]
Hey @dfm - 

#AstroHackWeek 2015 is coming up, and it would be good if the kids can corner plot their sampled PDFs with PJM-compliant filled contours etc (nicely nailed by your good self in #41 and #45). What do you think about updating the package so that `pip install --upgrade traiangle_plot` gives them this new power?

Thanks!

**Comment by dfm** [comment]
Done and done. `pip install -U --no-deps triangle_plot` should give you version `0.2.0`.

P.S. **always** use `--no-deps` just in case. If you don't a world of horror can come crashing down on you. I'll never understand why that's not the default!!!

**Comment by drphilmarshall** [comment]
Thanks @dfm! 

@abmantz - your 2D credible intervals can now be filled in! :-)
