### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by kbarbary** [dfm/triangle.py#59]
I've bugged Dan about this before on twitter. :)

There's considerable confusion caused by names in this module: The module name is `triangle`, the pypi name is "triangle_plot," the repo name is "triangle.py," and the main entry point within the package is `corner()`. Results of the confusion: #39 and #28.

I suggest renaming all of these to simply `corner`, which is miraculously unclaimed on PyPI. You get:

- `pip install corner`
- `from corner import corner` or `import corner; corner.corner(...)`

(I'm not so set on the name, just the consistency.)

Two possible downsides:
- There could still be conflicts with other PyPI packages if any of them provide a `corner` module or package (despite not being named "corner"). However, I didn't see any obvious candidates for this when searching "corner" on PyPI.
- Dan might not want to rename the repo, since it is so popular. I would think github redirects would take care of this though?

Any thoughts on the color of this bikeshed?

**Comment by drphilmarshall** [comment]
I'm in favour of this switch. Corner is a good name ;-)

**Comment by dfm** [comment]
It is no longer available :wink: https://pypi.python.org/pypi/corner; https://github.com/dfm/corner.py

**Comment by kbarbary** [comment]
That was fast :)  I suppose there's some reason you created a new repo instead of renaming? I think renaming would keep the forks/stars/watchers.

**Comment by dfm** [comment]
Nope: I'm just dumb. Doing that now! I somehow forgot that GitHub does have redirects.

**Comment by kbarbary** [comment]
Nice. My dreams have been fulfilled today.

**Comment by drphilmarshall** [comment]
Mine too! :-)

Did you rename to corner or corner.py? I'd go for the former myself. Then-
does it make sense to rename the main def as "plot" in order to, you know,
make a cornerplot?

**Comment by drphilmarshall** [comment]
I guess adding a plot method that just calls corner is the better way to do
this though, to avoid breaking everyone's code even further :-)

**Comment by dfm** [comment]
Well that took some git foo! But everything is properly migrated now. Thanks @kbarbary and @drphilmarshall. I have been wanting to do this!

You now install using:

```
pip install corner
```

and run:

```
import corner
corner.corner(...)
```

If you install `triangle_plot` it will continue working as a shim to `corner.py` but it throws a deprecation warning.

I don't like calling the function `plot` because I'd rather be able to do

```
from corner import corner
```

It would, of course, be even better to enable:

```
from corner.corner import corner as cornerplot
```

but who has time for that :wink:

**Comment by drphilmarshall** [comment]
:-)

Thanks a lot Dan, this is great.

I think I'll just munge my data into an array called "plot" and then do
```
import corner
corner(plot)
```
;-)
